# Generated by Django 5.2.3 on 2025-06-28 03:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='konten',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
